2025-03-29 16:13:54,028 DEBUG    root            Loaded Command Group: ['gcloud', 'compute']
2025-03-29 16:13:54,031 DEBUG    root            Loaded Command Group: ['gcloud', 'compute', 'firewall_rules']
2025-03-29 16:13:54,040 DEBUG    root            Loaded Command Group: ['gcloud', 'compute', 'firewall-rules', 'list']
2025-03-29 16:13:54,048 DEBUG    root            Running [gcloud.compute.firewall-rules.list] with arguments: [--format: "table(name,network,direction,priority,sourceRanges,allowed,targetTags)"]
2025-03-29 16:13:54,366 DEBUG    root            Chosen display Format:    table(
      name,
      network.basename(),
      direction,
      priority,
      allowed[].map().firewall_rule().list():label=ALLOW,
      denied[].map().firewall_rule().list():label=DENY,
      disabled
    ) table(name,network,direction,priority,sourceRanges,allowed,targetTags)
2025-03-29 16:13:54,367 INFO     root            Display format: "    table(
      name,
      network.basename(),
      direction,
      priority,
      allowed[].map().firewall_rule().list():label=ALLOW,
      denied[].map().firewall_rule().list():label=DENY,
      disabled
    ) table(name,network,direction,priority,sourceRanges,allowed,targetTags)"
2025-03-29 16:13:54,370 DEBUG    urllib3.connectionpool Starting new HTTPS connection (1): compute.googleapis.com:443
2025-03-29 16:13:54,410 DEBUG    urllib3.connectionpool https://compute.googleapis.com:443 "GET /compute/v1/projects/silken-quasar-455114-g9/global/firewalls?alt=json&maxResults=500 HTTP/11" 403 None
2025-03-29 16:13:54,414 DEBUG    root            Chosen display Format:list[title="Some requests did not succeed:",always-display-title]
2025-03-29 16:13:54,414 DEBUG    root            (gcloud.compute.firewall-rules.list) Some requests did not succeed:
 - Request had insufficient authentication scopes.
Traceback (most recent call last):
  File "/snap/google-cloud-cli/320/lib/googlecloudsdk/calliope/cli.py", line 981, in Execute
    resources = calliope_command.Run(cli=self, args=args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/google-cloud-cli/320/lib/googlecloudsdk/calliope/backend.py", line 937, in Run
    ).Display()
      ^^^^^^^^^
  File "/snap/google-cloud-cli/320/lib/googlecloudsdk/calliope/display.py", line 507, in Display
    self._printer.Print(self._resources)
  File "/snap/google-cloud-cli/320/lib/googlecloudsdk/core/resource/resource_printer_base.py", line 301, in Print
    for resource in resources:
                    ^^^^^^^^^
  File "/snap/google-cloud-cli/320/lib/googlecloudsdk/core/util/peek_iterable.py", line 211, in __next__
    item = self._NextItem()
           ^^^^^^^^^^^^^^^^
  File "/snap/google-cloud-cli/320/lib/googlecloudsdk/core/util/peek_iterable.py", line 183, in _NextItem
    return next(self._iterable)
           ^^^^^^^^^^^^^^^^^^^^
  File "/snap/google-cloud-cli/320/lib/googlecloudsdk/api_lib/compute/lister.py", line 1010, in __call__
    utils.RaiseException(errors, ListException)
  File "/snap/google-cloud-cli/320/lib/googlecloudsdk/api_lib/compute/utils.py", line 148, in RaiseException
    raise exception(
googlecloudsdk.api_lib.compute.lister.ListException: Some requests did not succeed:
 - Request had insufficient authentication scopes.

2025-03-29 16:13:54,418 ERROR    root            (gcloud.compute.firewall-rules.list) Some requests did not succeed:
 - Request had insufficient authentication scopes.

